stages:
  - build  

build_job:
  stage: build
  only:
    - branches
  script:
    - 'cd ConsoleApp2'
    - 'ls'
    - './ConsoleApp2.sln'  
  artifacts:
    paths:
      - 'ConsoleApp2\ConsoleApp2\bin\Debug\ConsoleApp2.exe'
