stages:
  - build  

build_job:
  stage: build
  only:
    - branches
  script:
    - 'cd ConsoleApp2'
    - 'ls'
    - 'cd ConsoleApp2'
    - 'cd bin'
    - 'cd Release'
    - 'cd netcoreapp2.1'
    - 'cd win-x64'
    - './ConsoleApp2.exe'
    - './nuget.exe restore'
    - './ConsoleApp2.sln'  
  artifacts:
    paths:
      - 'ConsoleApp2\ConsoleApp2\bin\Debug\ConsoleApp2.exe'
