stages:
  - build  

build_job:
  stage: build
  only:
    - branches
  script:
    - 'cd ConsoleApp2'
    - 'nuget.exe start'
    - 'cd C:\Users\idina\Downloads\nuget.exe restore'
    - '& C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSbuild.exe" ConsoleApp2.sln'  
  artifacts:
    paths:
      - 'ConsoleApp2\ConsoleApp2\bin\Debug\ConsoleApp2.exe'
